upgrade: fix adminrepochecks on missing repositories
when just one product has missing repositories and another one
shows empty (successful) repochecks, we need to skip trying to
parse the missing repositories when there aren't any.

fixes: NoMethodError (undefined method `to_sym' for nil:NilClass)