crowbar: Fix attribute method in nodes controller
It was calling .to_a on the path parameter while it was in the form of
"path/to/some/attribute". So that failed:

NoMethodError (undefined method `to_a' for "state":String):
  app/controllers/nodes_controller.rb:502:in `attribute'