upgrade: restart nova services after upgrade
After upgrading from Pike to Rocky, nova-compute services
are all failing with this error message:

  Failed to allocate the network(s), not rescheduling.

which is logged as:

  NovaException: In shutdown, no new events can be scheduled

This is actually an oslo.service bug:

  https://bugs.launchpad.net/nova/+bug/1715374

which has not been fixed so far. Restart is the workaround
that was pushed upstream.