avoid v4.1.5 of gem delayed_job_active_record
There was a breaking change in version 4.1.5 of the gem
delayed_job_active_record:
https://github.com/collectiveidea/delayed_job_active_record/issues/185

Resulting failure:
$ bin/rake db:create db:migrate
[...]
NameError: undefined method `reserve' for class `Class'
/home/travis/build/crowbar/crowbar-core/crowbar_framework/config/initializers/delayed_job_log_silencer.rb:22:in `alias_method'
[...]