crowbar: Avoid nil crash on applying errored nodes
When a node is in error state, it seems the chef apply fails
with

[2017-11-03T00:42:02-04:00] FATAL: NoMethodError: undefined method `key?' for nil:NilClass

This is due to "applying_for" not being set.

(cherry picked from commit 96cb9b6f24b2ceeb1cc806b33eb23fdde6b02d46)